spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:sagan;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  basic:
    enabled: false
  require_ssl: false
  ignored:
    - /lib/**
    - /css/**
    - /font-custom/**
    - /img/**
    - /500
    - /404

application:
  security:
    jwt:
      secret-key: jakaza
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
