spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://ep-red-base-a5shenla.us-east-2.aws.neon.tech/storedb?user=storedb_owner&password=mqgV5M0TDaCr&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


security:
  basic:
    enabled: false
  require_ssl: false
  ignored:
    - /lib/**
    - /css/**
    - /font-custom/**
    - /img/**
    - /500
    - /404

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
